name: Docs
on:
  push:
    branches: [main, restructure/monorepo]
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install .[dev]
          pip install sphinx sphinx-autodoc-typehints sphinx-rtd-theme
      - name: Build docs
        run: sphinx-build -W doc/source _build/html
